=== nsstnc/cli-fastapi-json/cli/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "kind": {
      "type": "string",
      "maxLength": 32,
      "default": "MyKind"
    },
    "name": {
      "type": "string",
      "maxLength": 128
    },
    "version": {
      "type": "string",
      "pattern": "^\\d+\\.\\d+\\.\\d+(-[a-zA-Z0-9]+(\\.[a-zA-Z0-9]+)*)?(\\+[a-zA-Z0-9]+(\\.[a-zA-Z0-9]+)*)?$"
    },
    "description": {
      "type": "string",
      "maxLength": 4096
    },
    "configuration": {
      "type": "object",
      "properties": {
        "specification": {
          "type": "object",
          "additionalProperties": true
        },
        "settings": {
          "type": "object",
          "additionalProperties": true
        }
      },
      "required": ["specification", "settings"]
    }
  },
  "required": ["kind", "name", "version", "description", "configuration"]
}

=== nsstnc/cli-fastapi-json/cli/kind.json
{
  "kind": "MyModel",
  "name": "hello-world",
  "version": "1.0.0",
  "description": "My application",
  "configuration": {
    "specification": {
      "jvmConfig": [
        "-Dcom.sun.a=a",
        "-Dcom.sun.b=b",
        "-Dcom.sun.c=c"
      ],
      "exposedPorts": [
        {
          "name": "my-port",
          "port": 8000,
          "protocol": "TCP"
        }
      ],
      "sharedNamespace": true,
      "log": {
        "level": "INFO"
      },
      "environmentVariables": [
        "VAR1=VALUE1"
      ]
    },
    "settings": {
    }
  }
}
